package com.charactergenerator.reyerta.domain.enumeration;

/**
 * The IncrustacionesArmadura enumeration.
 */
public enum IncrustacionesArmadura {
    ACORAZADA_MENOR, ATRAYENTE_MENOR, CURATIVA_BASICA, ESCAPISTA, FLEXIBLE, OPACA, PROTECTORA, SILENCIOSA, REFORZADA_MENOR, ACORAZADA, ANARQUICA, ATRAYENTE, AXIOMATICA, CAMBIANTE, CURATIVA_CRITICA, PROFANA, RESISTENTE_MENOR, SAGRADA, VALIENTE, ACORAZADA_MAYOR, ATRAYENTE_MAYOR, CURATIVA_SEVERA, ETEREA, INDESTRUCTIBLE, REFORZADA, RESISTENTE, DESAFIANTE, RESISTENTE_MAYOR, REFORZADA_MAYOR, REDENTORA, ACORAZADO_MENOR, ALIENTODRAGON, BATIENTE, CAUSTICO_MENOR, CECADOR, CONCUSION, PROTECTOR, PUNZANTE, ACORAZADO, CAUSTICO, REFLEJANTE_MENOR, ACORAZADO_MAYOR, CAUTICO_MAYOR, FLOTANTE, REFLEJANTE, REFLEJANTE_MAYOR, NONE
}
