package com.charactergenerator.reyerta.domain.enumeration;

/**
 * The IncrustacionesArma enumeration.
 */
public enum IncrustacionesArma {
    AMENAZANTE, ANULANTE_MENOR, ARROJADIZA, ATINANTE, BALANCEADA, BRILALNTE, CASTIGADORA, COMPASIVA, CORROSIVA, DEFENSORA, DISTANTE, ENCANTADA_MENOR, FILOSA, PROTECTORA, RETORNANTE, VICTORIOSA, DINAMO, ANARQUICA, ANULANTE, AXIOMATICA, CONTUNDENTE, ENCANTADA, LACERANTE, PROFANA, SAGRADA, VAMPIRICA, RADIANTE, DINAMO_OPTIMIZADO, ANIMADA, ANULANTE_MAYOR, BUSCADORA, ETEREA, ENCANTADA_MAYOR, INVISIBLE, INVOCABLE, VELOZ, RADIANTE_EXPLOSIVA, EXORCISTA, INDESTRUCTIBLE, EJECUTORA, SOLARIANA, NONE
}
